title: oscarrcruz.github.io
logo: /assets/img/logo.png
description: IT professional with expertise in network engineering, vulnerability management, and cybersecurity. He holds certifications including CompTIA CySA+, Security+, Network+, A+, and CCNA, and has worked with companies like Cisco and Qualys to deliver secure and scalable solutions. Showcasing cybersecurity insights from projects and other websites.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
