title: oscarrcruz.github.io
author:
  name: "Oscar Martinez"
  avatar: "/assets/images/avatar.jpg"
  bio: "IT professional, Cybersecurity Specialist and Problem Solver"
  location: "Raleigh, NC"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/oscar-m-78507280"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/<your-username>"
    - label: "TryHackMe"
      icon: "fas fa-terminal"
      url: "https://tryhackme.com/p/oskycruz"
logo: /assets/img/logo.png
description: "IT professional ,Cybersecurity Specialist and Problem Solver"
google_analytics:
remote_theme: mmistakes/minimal-mistakes

 
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
   
excerpt_separator: <!--more-->
defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      author_profile: true
      is_post: true
      permalink: /blog/:categories/:title/
      layout: single
      read_time: true
      comments: false
      share: false
      show_date: true
      related: false



